[2020-09-18 15:16:51] request.INFO: Matched route "solicitud". {"route":"solicitud","route_parameters":{"_route":"solicitud","id":"8","_controller":"App\\Controller\\GestionController::solicitudAction"},"request_uri":"https://localhost:8000/gestionMantenimiento/solicitud/8","method":"GET"} []
[2020-09-18 15:16:51] security.DEBUG: Read existing security token from the session. {"key":"_security_main","token_class":"Symfony\\Component\\Security\\Core\\Authentication\\Token\\UsernamePasswordToken"} []
[2020-09-18 15:16:51] security.DEBUG: User was reloaded from a user provider. {"provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider","username":"alejandro.vinuelas@upm.es"} []
[2020-09-18 15:16:51] security.DEBUG: Access denied, the user is neither anonymous, nor remember-me. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at C:\\symfony4LOCAL\\SolMan\\vendor\\symfony\\security-http\\Firewall\\AccessListener.php:91)"} []
[2020-09-18 15:16:51] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: "Access Denied." at C:\symfony4LOCAL\SolMan\vendor\symfony\security-http\Firewall\ExceptionListener.php line 137 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException(code: 0): Access Denied. at C:\\symfony4LOCAL\\SolMan\\vendor\\symfony\\security-http\\Firewall\\ExceptionListener.php:137, Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at C:\\symfony4LOCAL\\SolMan\\vendor\\symfony\\security-http\\Firewall\\AccessListener.php:91)"} []
[2020-09-18 15:16:53] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2020-09-18 15:17:08] request.INFO: Matched route "solicitud". {"route":"solicitud","route_parameters":{"_route":"solicitud","id":"8","_controller":"App\\Controller\\GestionController::solicitudAction"},"request_uri":"https://localhost:8000/gestionMantenimiento/solicitud/8","method":"GET"} []
[2020-09-18 15:17:08] security.DEBUG: Read existing security token from the session. {"key":"_security_main","token_class":"Symfony\\Component\\Security\\Core\\Authentication\\Token\\UsernamePasswordToken"} []
[2020-09-18 15:17:08] security.DEBUG: User was reloaded from a user provider. {"provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider","username":"alejandro.vinuelas@upm.es"} []
[2020-09-18 15:17:08] security.DEBUG: Access denied, the user is neither anonymous, nor remember-me. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at C:\\symfony4LOCAL\\SolMan\\vendor\\symfony\\security-http\\Firewall\\AccessListener.php:91)"} []
[2020-09-18 15:17:08] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: "Access Denied." at C:\symfony4LOCAL\SolMan\vendor\symfony\security-http\Firewall\ExceptionListener.php line 137 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException(code: 0): Access Denied. at C:\\symfony4LOCAL\\SolMan\\vendor\\symfony\\security-http\\Firewall\\ExceptionListener.php:137, Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at C:\\symfony4LOCAL\\SolMan\\vendor\\symfony\\security-http\\Firewall\\AccessListener.php:91)"} []
[2020-09-18 15:17:08] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2020-09-18 15:27:44] request.INFO: Matched route "solicitud". {"route":"solicitud","route_parameters":{"_route":"solicitud","id":"8","_controller":"App\\Controller\\GestionController::solicitudAction"},"request_uri":"https://localhost:8000/gestionMantenimiento/solicitud/8","method":"GET"} []
[2020-09-18 15:27:44] security.DEBUG: Read existing security token from the session. {"key":"_security_main","token_class":"Symfony\\Component\\Security\\Core\\Authentication\\Token\\UsernamePasswordToken"} []
[2020-09-18 15:27:44] security.DEBUG: User was reloaded from a user provider. {"provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider","username":"alejandro.vinuelas@upm.es"} []
[2020-09-18 15:27:44] security.DEBUG: Access denied, the user is neither anonymous, nor remember-me. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at C:\\symfony4LOCAL\\SolMan\\vendor\\symfony\\security-http\\Firewall\\AccessListener.php:91)"} []
[2020-09-18 15:27:44] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: "Access Denied." at C:\symfony4LOCAL\SolMan\vendor\symfony\security-http\Firewall\ExceptionListener.php line 137 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException(code: 0): Access Denied. at C:\\symfony4LOCAL\\SolMan\\vendor\\symfony\\security-http\\Firewall\\ExceptionListener.php:137, Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at C:\\symfony4LOCAL\\SolMan\\vendor\\symfony\\security-http\\Firewall\\AccessListener.php:91)"} []
[2020-09-18 15:27:44] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2020-09-18 15:29:13] request.INFO: Matched route "solicitud". {"route":"solicitud","route_parameters":{"_route":"solicitud","id":"8","_controller":"App\\Controller\\GestionController::solicitudAction"},"request_uri":"https://localhost:8000/gestionMantenimiento/solicitud/8","method":"GET"} []
[2020-09-18 15:29:13] security.DEBUG: Read existing security token from the session. {"key":"_security_main","token_class":"Symfony\\Component\\Security\\Core\\Authentication\\Token\\UsernamePasswordToken"} []
[2020-09-18 15:29:13] security.DEBUG: User was reloaded from a user provider. {"provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider","username":"alejandro.vinuelas@upm.es"} []
[2020-09-18 15:29:13] security.DEBUG: Access denied, the user is neither anonymous, nor remember-me. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at C:\\symfony4LOCAL\\SolMan\\vendor\\symfony\\security-http\\Firewall\\AccessListener.php:91)"} []
[2020-09-18 15:29:13] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: "Access Denied." at C:\symfony4LOCAL\SolMan\vendor\symfony\security-http\Firewall\ExceptionListener.php line 137 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException(code: 0): Access Denied. at C:\\symfony4LOCAL\\SolMan\\vendor\\symfony\\security-http\\Firewall\\ExceptionListener.php:137, Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at C:\\symfony4LOCAL\\SolMan\\vendor\\symfony\\security-http\\Firewall\\AccessListener.php:91)"} []
[2020-09-18 15:29:14] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2020-09-18 15:29:31] request.INFO: Matched route "solicitud". {"route":"solicitud","route_parameters":{"_route":"solicitud","id":"27","_controller":"App\\Controller\\GestionController::solicitudAction"},"request_uri":"https://localhost:8000/gestionMantenimiento/solicitud/27","method":"GET"} []
[2020-09-18 15:29:31] security.DEBUG: Read existing security token from the session. {"key":"_security_main","token_class":"Symfony\\Component\\Security\\Core\\Authentication\\Token\\UsernamePasswordToken"} []
[2020-09-18 15:29:31] security.DEBUG: User was reloaded from a user provider. {"provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider","username":"alejandro.vinuelas@upm.es"} []
[2020-09-18 15:29:31] security.DEBUG: Access denied, the user is neither anonymous, nor remember-me. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at C:\\symfony4LOCAL\\SolMan\\vendor\\symfony\\security-http\\Firewall\\AccessListener.php:91)"} []
[2020-09-18 15:29:31] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: "Access Denied." at C:\symfony4LOCAL\SolMan\vendor\symfony\security-http\Firewall\ExceptionListener.php line 137 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException(code: 0): Access Denied. at C:\\symfony4LOCAL\\SolMan\\vendor\\symfony\\security-http\\Firewall\\ExceptionListener.php:137, Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at C:\\symfony4LOCAL\\SolMan\\vendor\\symfony\\security-http\\Firewall\\AccessListener.php:91)"} []
[2020-09-18 15:29:31] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2020-09-18 15:30:08] request.INFO: Matched route "solicitud". {"route":"solicitud","route_parameters":{"_route":"solicitud","id":"8","_controller":"App\\Controller\\GestionController::solicitudAction"},"request_uri":"https://localhost:8000/gestionMantenimiento/solicitud/8","method":"GET"} []
[2020-09-18 15:30:08] security.DEBUG: Read existing security token from the session. {"key":"_security_main","token_class":"Symfony\\Component\\Security\\Core\\Authentication\\Token\\UsernamePasswordToken"} []
[2020-09-18 15:30:08] security.DEBUG: User was reloaded from a user provider. {"provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider","username":"alejandro.vinuelas@upm.es"} []
[2020-09-18 15:30:08] security.DEBUG: Access denied, the user is neither anonymous, nor remember-me. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at C:\\symfony4LOCAL\\SolMan\\vendor\\symfony\\security-http\\Firewall\\AccessListener.php:91)"} []
[2020-09-18 15:30:08] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: "Access Denied." at C:\symfony4LOCAL\SolMan\vendor\symfony\security-http\Firewall\ExceptionListener.php line 137 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException(code: 0): Access Denied. at C:\\symfony4LOCAL\\SolMan\\vendor\\symfony\\security-http\\Firewall\\ExceptionListener.php:137, Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at C:\\symfony4LOCAL\\SolMan\\vendor\\symfony\\security-http\\Firewall\\AccessListener.php:91)"} []
[2020-09-18 15:30:08] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2020-10-08 19:53:32] request.INFO: Matched route "home". {"route":"home","route_parameters":{"_route":"home","_controller":"App\\Controller\\DefaultController::homeAction"},"request_uri":"https://localhost:8000/","method":"POST"} []
[2020-10-08 19:53:32] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-08 19:53:35] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)" at C:\symfony4REMOTO\SolMan\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 93 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at C:\\symfony4REMOTO\\SolMan\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:93, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at C:\\symfony4REMOTO\\SolMan\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:31, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at C:\\symfony4REMOTO\\SolMan\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:27)"} []
[2020-10-08 20:10:19] request.INFO: Matched route "asignarSolicitud". {"route":"asignarSolicitud","route_parameters":{"_route":"asignarSolicitud","_controller":"App\\Controller\\GestionController::asignarSolicitudAction","id":"7"},"request_uri":"https://localhost:8000/gestionMantenimiento/asignarSolicitud/7","method":"GET"} []
[2020-10-08 20:10:19] security.DEBUG: Read existing security token from the session. {"key":"_security_main","token_class":"Symfony\\Component\\Security\\Core\\Authentication\\Token\\UsernamePasswordToken"} []
[2020-10-08 20:10:19] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)" at C:\symfony4REMOTO\SolMan\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 93 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at C:\\symfony4REMOTO\\SolMan\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:93, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at C:\\symfony4REMOTO\\SolMan\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:31, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at C:\\symfony4REMOTO\\SolMan\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:27)"} []
[2020-10-08 20:10:59] request.INFO: Matched route "asignarSolicitud". {"route":"asignarSolicitud","route_parameters":{"_route":"asignarSolicitud","_controller":"App\\Controller\\GestionController::asignarSolicitudAction","id":"7"},"request_uri":"https://localhost:8000/gestionMantenimiento/asignarSolicitud/7","method":"GET"} []
[2020-10-08 20:10:59] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-08 20:10:59] security.DEBUG: Access denied, the user is not fully authenticated; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at C:\\symfony4REMOTO\\SolMan\\vendor\\symfony\\security-http\\Firewall\\AccessListener.php:91)"} []
[2020-10-08 20:10:59] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\HttpException: "Full authentication is required to access this resource." at C:\symfony4REMOTO\SolMan\vendor\symfony\security-http\Firewall\ExceptionListener.php line 194 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\HttpException(code: 0): Full authentication is required to access this resource. at C:\\symfony4REMOTO\\SolMan\\vendor\\symfony\\security-http\\Firewall\\ExceptionListener.php:194, Symfony\\Component\\Security\\Core\\Exception\\InsufficientAuthenticationException(code: 0): Full authentication is required to access this resource. at C:\\symfony4REMOTO\\SolMan\\vendor\\symfony\\security-http\\Firewall\\ExceptionListener.php:146, Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at C:\\symfony4REMOTO\\SolMan\\vendor\\symfony\\security-http\\Firewall\\AccessListener.php:91)"} []
[2020-10-08 20:11:03] request.INFO: Matched route "solicitudes". {"route":"solicitudes","route_parameters":{"_route":"solicitudes","_controller":"App\\Controller\\GestionController::solicitudesAction"},"request_uri":"https://localhost:8000/gestionMantenimiento/solicitudes","method":"GET"} []
[2020-10-08 20:11:03] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2020-10-08 20:11:03] security.DEBUG: Access denied, the user is not fully authenticated; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at C:\\symfony4REMOTO\\SolMan\\vendor\\symfony\\security-http\\Firewall\\AccessListener.php:91)"} []
[2020-10-08 20:11:03] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\HttpException: "Full authentication is required to access this resource." at C:\symfony4REMOTO\SolMan\vendor\symfony\security-http\Firewall\ExceptionListener.php line 194 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\HttpException(code: 0): Full authentication is required to access this resource. at C:\\symfony4REMOTO\\SolMan\\vendor\\symfony\\security-http\\Firewall\\ExceptionListener.php:194, Symfony\\Component\\Security\\Core\\Exception\\InsufficientAuthenticationException(code: 0): Full authentication is required to access this resource. at C:\\symfony4REMOTO\\SolMan\\vendor\\symfony\\security-http\\Firewall\\ExceptionListener.php:146, Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at C:\\symfony4REMOTO\\SolMan\\vendor\\symfony\\security-http\\Firewall\\AccessListener.php:91)"} []
[2020-10-09 11:54:19] request.INFO: Matched route "home". {"route":"home","route_parameters":{"_route":"home","_controller":"App\\Controller\\DefaultController::homeAction"},"request_uri":"https://localhost:8000/","method":"GET"} []
[2020-10-09 11:54:19] security.DEBUG: Read existing security token from the session. {"key":"_security_main","token_class":"Symfony\\Component\\Security\\Core\\Authentication\\Token\\UsernamePasswordToken"} []
[2020-10-09 11:54:19] request.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)")." at C:\symfony4REMOTO\SolMan\templates\frontal\base.html.twig line 29 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): An exception has been thrown during the rendering of a template (\"An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)\"). at C:\\symfony4REMOTO\\SolMan\\templates\\frontal\\base.html.twig:29, Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at C:\\symfony4REMOTO\\SolMan\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:93, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at C:\\symfony4REMOTO\\SolMan\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:31, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES) at C:\\symfony4REMOTO\\SolMan\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:27)"} []
